{% set name = "microvenv" %}
{% set version = "2025.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/microvenv-{{ version }}.tar.gz
  sha256: 8a2568a8390a4ffb5af2f05e7642454e03b887e582d192b6316326974eab5d0f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - microvenv
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/brettcannon/microvenv
  summary: A minimal re-implementation of Python's venv module
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
