{% set name = "microvenv" %}
{% set version = "2023.3.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/microvenv-{{ version }}.tar.gz
  sha256: 6e8c80ccfe813b00b77ab9cc2e5af3fd44e2fe540df176509fda97123f8b8290

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7

test:
  imports:
    - microvenv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brettcannon/microvenv
  summary: A minimal re-implementation of Python's venv module
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
