{% set name = "microvenv" %}
{% set version = "2023.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/microvenv-{{ version }}.tar.gz
  sha256: 128c0c8ab46e3bbd7b4c902c8a5d6333b694f9ebf871f123b473425cb6fbe19f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7

test:
  imports:
    - microvenv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brettcannon/microvenv
  summary: A minimal re-implementation of Python's venv module
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
