schema_version: 1

context:
  name: microvenv
  version: 2025.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/microvenv-${{ version }}.tar.gz
  sha256: 8a2568a8390a4ffb5af2f05e7642454e03b887e582d192b6316326974eab5d0f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - microvenv
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: "A minimal re-implementation of Python's venv module"
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/brettcannon/microvenv

extra:
  recipe-maintainers:
    - thewchan
